table Calendario
	dataCategory: Time
	lineageTag: 88c3a605-9162-4992-b695-80f746b7c5cf

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 83df3c2c-8188-4c4d-962e-f46495a25aa1
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: c232473a-0b98-44f5-8943-e298f5ce9af5
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 7502dbf2-503a-4cf5-b1a0-eaec1cde1487
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: 92307e36-6b44-4b9e-8516-69d7ddb55d7a
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 420e3d25-25c4-4746-91f4-5f55d91d7a09
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Fechas = List.Dates(#date(2024, 1, 1), 731, #duration(1, 0, 0, 0)),
				    Tabla = Table.FromList(Fechas, Splitter.SplitByNothing(), {"Fecha"}),
				    Tipo = Table.TransformColumnTypes(Tabla, {{"Fecha", type date}}),
				    Anio = Table.AddColumn(Tipo, "Año", each Date.Year([Fecha]), Int64.Type),
				    NumMes = Table.AddColumn(Anio, "NumMes", each Date.Month([Fecha]), Int64.Type),
				    Mes = Table.AddColumn(NumMes, "Mes", each Date.ToText([Fecha], "MMM", "es-ES"), type text),
				    Trim = Table.AddColumn(Mes, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Fecha])), type text)
				in
				    Trim

	annotation PBI_ResultType = Table
