/// Calendario de fechas continuo, marcado como tabla de fecha. Filtra por esta
/// tabla y no por la fecha del hecho: es lo que hace funcionar la inteligencia de tiempo.
table Calendario
	dataCategory: Time
	lineageTag: 3422b078-cb8e-49b4-b636-f6d9572a0473

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 30dd7b65-6c6c-4032-b197-da1c6dd7f8db
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: b29dfad6-39be-43ce-b8bf-239391b13aba
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: ee564d14-9b32-4a42-9aeb-54337cd55937
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: e3bd85ea-9949-43c1-9b01-0cb710fee424
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 15871943-39ea-4c71-b922-b5ff73a6975c
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column EsDiaHabil
		dataType: string
		lineageTag: 128efb8f-3956-43d1-b648-af7df57c2cde
		summarizeBy: none
		sourceColumn: EsDiaHabil

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Calendario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"Año", Int64.Type},
				        {"Mes", type text},
				        {"NumMes", Int64.Type},
				        {"Trimestre", type text},
				        {"EsDiaHabil", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
