table Calendario
	dataCategory: Time
	lineageTag: e1a221be-ae58-471e-bde1-be66888fb15a

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 5fcfce86-b6ba-4596-a7dd-e99727c95aa7
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: efc324b3-8efb-462c-be7f-19d914e5e6ad
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: b7f214f6-577e-4db2-960d-734812fa36b6
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: 0292fe2a-7674-4c07-a032-75dc1f1bae76
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 05cbaf26-105e-47c6-8a90-1f1afcc5935c
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column EsDiaHabil
		dataType: string
		lineageTag: 22357fe0-ba7e-429a-aef9-804062785cfa
		summarizeBy: none
		sourceColumn: EsDiaHabil

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Calendario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"Año", Int64.Type},
				        {"Mes", type text},
				        {"NumMes", Int64.Type},
				        {"Trimestre", type text},
				        {"EsDiaHabil", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
