table Indicadores
	lineageTag: 27bf964f-74ea-4681-ba4a-559e959ed92b

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ddb17e4-bf2d-457f-9f72-4ca62d8d9360
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Sede'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1056279-bbbe-4ff1-991c-3b85892a59da
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column 'ID Servicio'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 11b067f8-0c81-4686-98b5-c6f219739c9d
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column 'ID Indicador'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6a6a0b22-aebc-410d-aa52-9def24ed0b73
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: ae1fa4e4-b44f-4d95-8bfe-b13ead602ba1
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column Den
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: a48041d8-e404-47a3-91f6-f71a930a1079
		summarizeBy: sum
		sourceColumn: Den

		annotation SummarizationSetBy = Automatic

	partition Indicadores = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicadores.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"ID Sede", Int64.Type},
				        {"ID Servicio", Int64.Type},
				        {"ID Indicador", Int64.Type},
				        {"Num", Int64.Type},
				        {"Den", Int64.Type}
				    }),
				    // descarta registros sin denominador (evita dividir por 0).
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Den] <> null and [Den] > 0)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table
