/// Hecho Indicadores. Grano: una fila por fecha, Sede, Servicio e indicador, con el patron
/// Num/Den. Las claves y las metricas base van ocultas: consulta el modelo con las medidas.
table Indicadores
	lineageTag: b23f6d44-5b75-481c-82b0-2d4e266a3fd7

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3e9ca453-f00c-4288-808b-80c40316de0b
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Sede'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f1f48015-0714-4f3c-9d2e-64408a9c086a
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column 'ID Servicio'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e85a685a-3cd0-4ba2-9071-6a4a163fbb10
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column 'ID Indicador'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aa13086c-2d82-40c7-8223-3ce2d43da70a
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: cb1bc106-88df-4d35-a6ce-10d56db87d9d
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column Den
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: c8bd28a5-017e-4476-ac71-2b062cba925b
		summarizeBy: sum
		sourceColumn: Den

		annotation SummarizationSetBy = Automatic

	partition Indicadores = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicadores.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"ID Sede", Int64.Type},
				        {"ID Servicio", Int64.Type},
				        {"ID Indicador", Int64.Type},
				        {"Num", Int64.Type},
				        {"Den", Int64.Type}
				    }),
				    // descarta registros sin denominador (evita dividir por 0).
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Den] <> null and [Den] > 0)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table
