/// Que mide cada fila del hecho. Segmenta por esta tabla para leer un indicador a
/// la vez: sumar varios mezclaria porcentajes con importes absolutos.
table Indicador
	lineageTag: 8dc9c1e1-1780-4867-9d20-bcb12621e505

	column 'ID Indicador'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 1b3ffac7-eb58-4721-a25f-3d64db865324
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: string
		lineageTag: e2e26ad1-5d35-4799-bb07-2b46f5f4f7ec
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 74b16898-f346-48fd-bb8b-c01fbfd7a6e5
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		isHidden
		lineageTag: 35346b92-bb62-46e3-b024-844aedb4b7a7
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition Indicador = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicador.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Indicador", Int64.Type},
				        {"Indicador", type text},
				        {"Tipo", type text},
				        {"Formato", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
