/// Hecho Indicadores. Grano: una fila por fecha, Sede, Servicio e indicador, con el patron
/// Num/Den. Las claves y las metricas base van ocultas: consulta el modelo con las medidas.
table Indicadores
	lineageTag: ef417db8-a451-408d-af50-b9980e7d8cbe

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5cc56065-0ded-49ca-b3e6-a2fae8a3ace7
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Sede'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 07eead99-9bb5-4b03-9c1f-a673e3a6f579
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column 'ID Servicio'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 34456d68-c97f-4cc6-8d88-1da6f0dddc80
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column 'ID Indicador'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 89ea6588-bc89-4584-99e6-da189f253425
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 39df1bdc-d93c-4a39-bcf5-2247e1adfe2c
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column Den
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 94aa7069-f127-44b9-95b1-7dec0f96f862
		summarizeBy: sum
		sourceColumn: Den

		annotation SummarizationSetBy = Automatic

	partition Indicadores = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicadores.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"ID Sede", Int64.Type},
				        {"ID Servicio", Int64.Type},
				        {"ID Indicador", Int64.Type},
				        {"Num", Int64.Type},
				        {"Den", Int64.Type}
				    }),
				    // descarta registros sin denominador (evita dividir por 0).
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Den] <> null and [Den] > 0)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table
