/// Que mide cada fila del hecho. Segmenta por esta tabla para leer un indicador a
/// la vez: sumar varios mezclaria porcentajes con importes absolutos.
table Indicador
	lineageTag: 75192c7b-e416-4980-b26d-03ed591707d9

	column 'ID Indicador'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 069065db-3180-478c-b3e5-63b6d92c5a8d
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: string
		lineageTag: d851b6a1-b21b-4350-bf01-03194f5ccd88
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 717214dc-60e2-4476-8c74-9dd0d76a1fed
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		isHidden
		lineageTag: 339f682e-55a6-487b-b5da-ea43ea1285c4
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition Indicador = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicador.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Indicador", Int64.Type},
				        {"Indicador", type text},
				        {"Tipo", type text},
				        {"Formato", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
