/// Dimension Sede: atributo por el que se corta el negocio. Una fila por miembro.
table Sede
	lineageTag: 6d1f96f5-05c7-482d-a491-23b4e90ff644

	column 'ID Sede'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 11ae4cf8-e214-4203-8508-b68d8b8919fb
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column Sede
		dataType: string
		lineageTag: 5d532752-f1d9-4fbe-8f32-f5591ce8f44e
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	partition Sede = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Sede.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Sede", Int64.Type},
				        {"Sede", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
