table Sede
	lineageTag: 237bace9-7726-4e67-944c-50be378d83c8

	column 'ID Sede'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 969fabf4-f825-44c9-aa35-b5ecaae6ca48
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column Sede
		dataType: string
		lineageTag: d61f8a74-e11d-4604-ac73-fee6645cca66
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	partition Sede = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Sede.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Sede", Int64.Type},
				        {"Sede", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
