/// Dimension Sede: atributo por el que se corta el negocio. Una fila por miembro.
table Sede
	lineageTag: aa13f055-3fff-4877-8f2f-2f042577b3f6

	column 'ID Sede'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: f4d23765-b4e2-4fc9-8fbb-13ad5d677091
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column Sede
		dataType: string
		lineageTag: 69ab5a52-1d51-4287-810b-cb82c14da6b9
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	partition Sede = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Sede.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Sede", Int64.Type},
				        {"Sede", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
