/// Dimension Sede: atributo por el que se corta el negocio. Una fila por miembro.
table Sede
	lineageTag: 6b61bb73-4e1b-4f52-85cf-9f587b2a3d73

	column 'ID Sede'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 20925f07-89de-448c-9d28-ab17aa8591ab
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column Sede
		dataType: string
		lineageTag: 8557ce20-45d0-4ecf-bb38-d2f62e442457
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	partition Sede = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Sede.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Sede", Int64.Type},
				        {"Sede", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
