/// Dimension Servicio, con la columna Servicio Agrupado para agrupar y jerarquizar.
table Servicio
	lineageTag: ec7f4918-c097-478a-9e9c-8bee5a2414ac

	column 'ID Servicio'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 7f28189c-c023-4c96-b25c-592efe22c149
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: string
		lineageTag: 3e0eedba-0819-41bf-af7e-4d52cb427e94
		summarizeBy: none
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	column 'Servicio Agrupado'
		dataType: string
		lineageTag: 535d98e3-79ec-40d4-84ec-14b743bd99dc
		summarizeBy: none
		sourceColumn: Servicio Agrupado

		annotation SummarizationSetBy = Automatic

	partition Servicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Servicio.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Servicio", Int64.Type},
				        {"Servicio", type text},
				        {"Servicio Agrupado", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
