/// Dimension Servicio, con la columna Servicio Agrupado para agrupar y jerarquizar.
table Servicio
	lineageTag: 804aad9e-7aa4-4d57-a8d9-1d6176e04890

	column 'ID Servicio'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: c52ac0ec-e1d3-431d-a682-aaaf89496245
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: string
		lineageTag: 3c75be22-0ac1-4e29-ba44-e526a910c424
		summarizeBy: none
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	column 'Servicio Agrupado'
		dataType: string
		lineageTag: 8ece8a14-0eb4-42d1-afa0-658ba05c47ca
		summarizeBy: none
		sourceColumn: Servicio Agrupado

		annotation SummarizationSetBy = Automatic

	partition Servicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Servicio.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Servicio", Int64.Type},
				        {"Servicio", type text},
				        {"Servicio Agrupado", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
