table Servicio
	lineageTag: 1a4f434d-2fa0-4687-896d-99e75311fe96

	column 'ID Servicio'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 25a435da-5519-4b39-b496-6b89c62dff0e
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: string
		lineageTag: b0da1dcd-5654-4e20-b43a-31034160837b
		summarizeBy: none
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	column 'Servicio Agrupado'
		dataType: string
		lineageTag: a17a76fe-5ebc-43ee-b0ff-d57be0f235b9
		summarizeBy: none
		sourceColumn: Servicio Agrupado

		annotation SummarizationSetBy = Automatic

	partition Servicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Servicio.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Servicio", Int64.Type},
				        {"Servicio", type text},
				        {"Servicio Agrupado", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
