/// Dimension Servicio, con la columna Servicio Agrupado para agrupar y jerarquizar.
table Servicio
	lineageTag: 5824eb75-633f-433b-934a-8c10930476f7

	column 'ID Servicio'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 9bca2ce0-9a55-42d0-8a9c-53bb2b1e84b4
		summarizeBy: none
		sourceColumn: ID Servicio

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: string
		lineageTag: f8d8d73c-bba5-4498-bf8f-dd534948bdd3
		summarizeBy: none
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	column 'Servicio Agrupado'
		dataType: string
		lineageTag: 5777f9a5-24fa-4500-b4f4-005d4e735f3b
		summarizeBy: none
		sourceColumn: Servicio Agrupado

		annotation SummarizationSetBy = Automatic

	partition Servicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Servicio.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Servicio", Int64.Type},
				        {"Servicio", type text},
				        {"Servicio Agrupado", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
