table Calendario
	dataCategory: Time
	lineageTag: 673fdf90-39e0-4894-82df-86efe0bfaca8

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 46a5d9cc-e7b6-4687-85ea-27f4c1c27b4d
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 94e70046-fd2b-473e-891f-8f821df3bbc4
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: c3937615-4bf6-46a9-8419-59f6cb0a6b23
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: 4617fe1a-ff03-4336-a79a-af11ac54e8c8
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 4e2498af-220d-426f-a115-bd73a1d686a1
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Fechas = List.Dates(#date(2024, 1, 1), 731, #duration(1, 0, 0, 0)),
				    Tabla = Table.FromList(Fechas, Splitter.SplitByNothing(), {"Fecha"}),
				    Tipo = Table.TransformColumnTypes(Tabla, {{"Fecha", type date}}),
				    Anio = Table.AddColumn(Tipo, "Año", each Date.Year([Fecha]), Int64.Type),
				    NumMes = Table.AddColumn(Anio, "NumMes", each Date.Month([Fecha]), Int64.Type),
				    Mes = Table.AddColumn(NumMes, "Mes", each Date.ToText([Fecha], "MMM", "es-ES"), type text),
				    Trim = Table.AddColumn(Mes, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Fecha])), type text)
				in
				    Trim

	annotation PBI_ResultType = Table
