/// Calendario de fechas continuo, marcado como tabla de fecha. Filtra por esta
/// tabla y no por la fecha del hecho: es lo que hace funcionar la inteligencia de tiempo.
table Calendario
	dataCategory: Time
	lineageTag: e45d3ca5-de64-4e11-b380-6dce7e315f34

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: a2f701b7-9c95-4aea-8e69-76a96e0b950b
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: b7085045-4adb-4046-9dee-46bd1761d0b9
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 79a5fc02-54f0-4e2b-a434-3f5a3ea0f544
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: 23a7d992-e573-4b82-abd1-b55386f4e7a7
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: e1c84d93-0286-4de3-9025-c2bfe47a39c8
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column EsDiaHabil
		dataType: string
		lineageTag: 2a6273e4-f6d8-41fa-9844-2314a16ab548
		summarizeBy: none
		sourceColumn: EsDiaHabil

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Calendario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"Año", Int64.Type},
				        {"Mes", type text},
				        {"NumMes", Int64.Type},
				        {"Trimestre", type text},
				        {"EsDiaHabil", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
