/// Calendario de fechas continuo, marcado como tabla de fecha. Filtra por esta
/// tabla y no por la fecha del hecho: es lo que hace funcionar la inteligencia de tiempo.
table Calendario
	dataCategory: Time
	lineageTag: 6dd78192-f589-4359-b261-cdea33e1f49f

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 8d8dcffa-fc09-46db-af0d-30b33c7fdb44
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 73c19944-32fc-459b-a623-40084f8ba72b
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: e29f797e-96d7-45c0-8d91-26568e66efe4
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: 01b83832-b733-4456-99f0-87648bf1b085
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 8ab48224-910a-41b9-a8ee-0f4b88ae086a
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column EsDiaHabil
		dataType: string
		lineageTag: 03f30981-e295-4501-a4a1-a4caa7eea8d0
		summarizeBy: none
		sourceColumn: EsDiaHabil

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Calendario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"Año", Int64.Type},
				        {"Mes", type text},
				        {"NumMes", Int64.Type},
				        {"Trimestre", type text},
				        {"EsDiaHabil", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
