/// Calendario de fechas continuo, marcado como tabla de fecha. Filtra por esta
/// tabla y no por la fecha del hecho: es lo que hace funcionar la inteligencia de tiempo.
table Calendario
	dataCategory: Time
	lineageTag: 0f978688-9d2f-4ba9-a495-8ba01d4f92cc

	column Fecha
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: fac6a5f7-9ad6-43fe-908e-360bb28e7487
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 046667d5-8837-43b8-b404-2e5928ff5077
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 95f030cf-06cc-4488-84a5-27f707983e13
		summarizeBy: none
		sourceColumn: Mes
		sortByColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column NumMes
		dataType: int64
		formatString: 0
		lineageTag: fe6e47f2-0961-42fc-8d7d-faa99069717d
		summarizeBy: none
		sourceColumn: NumMes

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: f760b448-c6e7-46ed-a7b1-8f04c4e4d025
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column EsDiaHabil
		dataType: string
		lineageTag: e9e4508e-4f9a-4f3d-be36-c860855eebdc
		summarizeBy: none
		sourceColumn: EsDiaHabil

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Calendario.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"Año", Int64.Type},
				        {"Mes", type text},
				        {"NumMes", Int64.Type},
				        {"Trimestre", type text},
				        {"EsDiaHabil", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
