/// Que mide cada fila del hecho. Segmenta por esta tabla para leer un indicador a
/// la vez: sumar varios mezclaria porcentajes con importes absolutos.
table Indicador
	lineageTag: 2cee061d-6718-4192-b850-94cc0a3cbed7

	column 'ID Indicador'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 45472bf7-1ee3-48bf-9369-4996d69aed1b
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: string
		lineageTag: a2579838-d7a3-4ff2-a441-c7ac7e61f05d
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: c5eb64ed-9fa7-46a8-9763-a44f5ab34cc5
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		isHidden
		lineageTag: 4c6eebc7-007f-410f-afbe-2298733c4eda
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition Indicador = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicador.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Indicador", Int64.Type},
				        {"Indicador", type text},
				        {"Tipo", type text},
				        {"Formato", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
