/// Que mide cada fila del hecho. Segmenta por esta tabla para leer un indicador a
/// la vez: sumar varios mezclaria porcentajes con importes absolutos.
table Indicador
	lineageTag: 7d5702d3-6667-44d1-9add-47faa1faf529

	column 'ID Indicador'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: ad37ab9c-101a-4253-9b45-5d0cd6a6cfe7
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: string
		lineageTag: 5f85c15a-06c9-4f85-8029-14bdb946b549
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 0e130e74-e46b-41cf-b4e1-cae45d307ee5
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		isHidden
		lineageTag: ecfd12a3-0110-4ca5-a19d-c48b745daff1
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition Indicador = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Indicador.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Indicador", Int64.Type},
				        {"Indicador", type text},
				        {"Tipo", type text},
				        {"Formato", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
