table Producto
	lineageTag: f89407e0-ca37-467e-9292-13d5c862d496

	column 'ID Producto'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 8d4f0ccf-dc26-4fb5-9b7f-e728b716487e
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		lineageTag: 6e94b55e-1c33-48bf-900d-3378d14177dc
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column 'Categoria Producto'
		dataType: string
		lineageTag: 9d04204d-df06-4552-abec-6821299277aa
		summarizeBy: none
		sourceColumn: Categoria Producto

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Producto.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Producto", Int64.Type},
				        {"Producto", type text},
				        {"Categoria Producto", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
