/// Dimension Producto, con la columna Categoria Producto para agrupar y jerarquizar.
table Producto
	lineageTag: 13d4da36-4c8d-421c-a538-0a47fa010b4a

	column 'ID Producto'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 2e317152-d9ce-4dc3-a524-079641a32e43
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		lineageTag: b220cfbe-f5ea-4312-95fb-0547199737ef
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column 'Categoria Producto'
		dataType: string
		lineageTag: 25d3d5eb-2566-411d-9eec-22f12499b873
		summarizeBy: none
		sourceColumn: Categoria Producto

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Producto.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Producto", Int64.Type},
				        {"Producto", type text},
				        {"Categoria Producto", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
