/// Dimension Producto, con la columna Categoria Producto para agrupar y jerarquizar.
table Producto
	lineageTag: d9fa6f66-9a46-4552-b77b-ab1718a73b1f

	column 'ID Producto'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 38e16448-1c70-4e1b-bba8-1c59b5a109c4
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		lineageTag: 42cbb3a1-611e-45b5-8e8b-a3ff28c95f1d
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column 'Categoria Producto'
		dataType: string
		lineageTag: 78b11f6e-1591-48e2-b77e-afb51674246b
		summarizeBy: none
		sourceColumn: Categoria Producto

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Producto.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Producto", Int64.Type},
				        {"Producto", type text},
				        {"Categoria Producto", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
