/// Dimension Producto, con la columna Categoria Producto para agrupar y jerarquizar.
table Producto
	lineageTag: 57806c25-2628-42a4-878f-96743ed41f8a

	column 'ID Producto'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 760b72e8-2ede-41a2-9a7c-beb4e97affcd
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		lineageTag: 73ec8135-c3c2-4d73-b1e6-3a4f325792a9
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column 'Categoria Producto'
		dataType: string
		lineageTag: be4e920a-6697-4a4a-99e6-c112c0ffd38f
		summarizeBy: none
		sourceColumn: Categoria Producto

		annotation SummarizationSetBy = Automatic

	partition Producto = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Producto.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Producto", Int64.Type},
				        {"Producto", type text},
				        {"Categoria Producto", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
