table Region
	lineageTag: f7dee4c6-dc42-45af-8815-4c2fb831315c

	column 'ID Region'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 310e2adb-3a83-4df6-9b27-4f8b3140146b
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 9756a801-9cfa-4219-ade3-a31c7c7e6055
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Region.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Region", Int64.Type},
				        {"Region", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
