/// Dimension Region: atributo por el que se corta el negocio. Una fila por miembro.
table Region
	lineageTag: 59f47aae-ff51-40f8-8b10-b2c5affae564

	column 'ID Region'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: c7c9e6c9-94b1-497e-9428-e9a23fb3c9f6
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 30543bd6-d621-48f7-ac1b-177da022af28
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Region.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Region", Int64.Type},
				        {"Region", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
