/// Dimension Region: atributo por el que se corta el negocio. Una fila por miembro.
table Region
	lineageTag: a6acc2c3-aa5c-4829-a0ae-2250bdf5019d

	column 'ID Region'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: e3a48cf1-d529-45cf-a61a-6795393c688f
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6e2c30f9-9c1e-4fb2-9ece-0b0250000617
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Region.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Region", Int64.Type},
				        {"Region", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
