/// Dimension Region: atributo por el que se corta el negocio. Una fila por miembro.
table Region
	lineageTag: c4de0979-9105-4422-be7e-76a994716c34

	column 'ID Region'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 8a13ff2a-7e53-48dc-9ef0-f14e812b6d65
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: dba6f8cd-9f3b-477c-8cec-9707efe50281
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Region.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Region", Int64.Type},
				        {"Region", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
