/// Dimension Region: atributo por el que se corta el negocio. Una fila por miembro.
table Region
	lineageTag: e9c69a59-e37b-4503-9ead-9661d5062f66

	column 'ID Region'
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 7e5ac2af-2dbc-4368-9f6b-ddfd04472b13
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4bc49f66-38bb-4153-9234-495582d23378
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Region.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"ID Region", Int64.Type},
				        {"Region", type text}
				    })
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table
