/// Hecho Ventas. Grano: una fila por fecha, Region, Producto e indicador, con el patron
/// Num/Den. Las claves y las metricas base van ocultas: consulta el modelo con las medidas.
table Ventas
	lineageTag: 93d33931-93c6-470b-9772-393c7849c7d3

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 907a5260-2203-4cc5-828d-62b9e505ae1e
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Region'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1534a480-b1f7-413b-af2a-1fb157dbf160
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column 'ID Producto'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 01da1194-2dc4-44f0-b0ea-dd95f4535271
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column 'ID Indicador'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2e2766ca-23ef-46a1-bfc4-e064696026ab
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: a6b4465d-6fa4-4fd1-96d8-996fd9e75eec
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column Den
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 1b0e5981-25c3-4f9a-b096-3e054ff71574
		summarizeBy: sum
		sourceColumn: Den

		annotation SummarizationSetBy = Automatic

	partition Ventas = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Ventas.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"ID Region", Int64.Type},
				        {"ID Producto", Int64.Type},
				        {"ID Indicador", Int64.Type},
				        {"Num", Int64.Type},
				        {"Den", Int64.Type}
				    }),
				    // descarta registros sin denominador (evita dividir por 0).
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Den] <> null and [Den] > 0)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table
