/// Hecho Ventas. Grano: una fila por fecha, Region, Producto e indicador, con el patron
/// Num/Den. Las claves y las metricas base van ocultas: consulta el modelo con las medidas.
table Ventas
	lineageTag: 54d84de6-0b2c-4a4a-be91-f5992ab3bc16

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8aa89122-e15e-4f59-92b1-fe30e9e0c6f9
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Region'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 31eb57ad-31de-4a8d-84b6-516744342933
		summarizeBy: none
		sourceColumn: ID Region

		annotation SummarizationSetBy = Automatic

	column 'ID Producto'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 574dc0e0-e332-4d51-85f5-ff3a98ae4c98
		summarizeBy: none
		sourceColumn: ID Producto

		annotation SummarizationSetBy = Automatic

	column 'ID Indicador'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5e9d4e4a-bdca-4dc6-a9de-49a494299816
		summarizeBy: none
		sourceColumn: ID Indicador

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: e0a17cef-c3a2-4add-a79f-f178e788842b
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column Den
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 92eaea3e-c48f-45f6-98d0-086c962f993e
		summarizeBy: sum
		sourceColumn: Den

		annotation SummarizationSetBy = Automatic

	partition Ventas = m
		mode: import
		source =
				let
				    Origen = Csv.Document(
				        File.Contents(RutaBase & "\Ventas.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    EncabezadosPromovidos = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(EncabezadosPromovidos, {
				        {"Fecha", type date},
				        {"ID Region", Int64.Type},
				        {"ID Producto", Int64.Type},
				        {"ID Indicador", Int64.Type},
				        {"Num", Int64.Type},
				        {"Den", Int64.Type}
				    }),
				    // descarta registros sin denominador (evita dividir por 0).
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [Den] <> null and [Den] > 0)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table
